### ISSUE TITLE
[Enhancement] Improve message format on commit

### ISSUE THREAD

**Issue by biels** [requilence/integram#27]
You should look at the bot @GitHubBot and see how it displays commit and issue messages. 
![image](https://cloud.githubusercontent.com/assets/5158960/22950241/3f8d4aee-f305-11e6-9bf7-86d4b0d7083a.png)
I am using Integram with Bitbucket. The main problem is that if you provide a direct url, telegram renders it along with a giant profile picture on mobile devices. This quickly floods development groups. 

I think implementing an output format like the one above shouldn't be difficult at all. If you point me in the right direction I could even make a pull request for you. Thanks!

Edit: Took a look at the code, the changes should be made around here: https://github.com/Requilence/integram/blob/master/services/bitbucket/webhook.go#L340

**Comment by Requilence** [comment]
Hi! This was not a bug but feature 😀 But I agree with you. The commit messages should be more compact. I fixed that @f8a992dc48002089b4533175c9e1cde2610c0621 and deployed to production

**Comment by biels** [comment]
Wow! Tanks for the quick fix! Tested it and looks way better.
For now, closing. If I see something else or have another idea I will create another issue for that.

**Comment by biels** [comment]
This issue is not fixed yet for more than one commit in the same push. The message gets really messy. Could the design be like the one posted in the first issue?
[Hammer emoji] [n] new commit[s] to [Repo]:[Branch]:
[commit 1 hash with link]: [Message] by [User name]
[commit 2 hash with link]: [Message] by [User name]
[commit n hash with link]: [Message] by [User name]
And if the message starts to get past a certain length then start doing ellipsis on commit messages and finally if there are more than n commits (for example 6) add "and n more" with a link to commits page.
